# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: SFTP uploader w/options
        # You may pin to the exact commit or the version.
        # uses: zurb/sftp-upload-action@570d645b0fbf7fdd7c7fe6d5291ae5e0f2db5a08
        uses: zurb/sftp-upload-action@1.3
        with:
          # 
          host: ${{ secrets.FTP_SERVER_NAME}}
          # 
          port: 22 # optional, default is 22
          # 
          username: ${{ secrets.FTP_SERVER_USER}} # optional, default is root
          # 
          password: ${{ secrets.FTP_SERVER_PW}}
          # 
          localDir: /
          # 
          remoteDir: /
          # 
          dryRun: false # optional
          # 
          excludeMode: ignore # optional, default is remove
          # 
          forceUpload: false # optional
          # 
          exclude: "['projects/', 'test']" # optional, default is []
          # 
          concurrency: 100 # optional, default is 100
